.\" Process this file with
.\" groff -man -Tascii rhc-snapshot.1
.\"
.TH RHC_SNAPSHOT 1 "JANUARY 2011" Linux "User Manuals"
.SH NAME
rhc-snapshot \- Pulls down an application snapshot as gzipped tarfile
.SH SYNOPSIS
.B rhc-snapshot [-p
.I password
.B ]
.B [-s
.I pathname
.B ] [-r
.I pathname
.B ][-d] [-h]
.B [-l
.I rhlogin
.B ] -a
.I application_name
.SH DESCRIPTION
.B rhc-snapshot
pulls down an application snapshot as gzipped tarfile.  To create
an application use the
.BR rhc-create-app (1)
command.
.SH OPTIONS
.IP "-l|--rhlogin login"
Red Hat login (RHN or OpenShift login with OpenShift Express access)
.IP "-p|--password password"
RHLogin password
.IP "-a|--app application_name"
Name of application to snapshot
.IP "-s|--save pathname"
Saves entire application in an archive.  Pathname default:
.I ./$APPNAME.tar.gz
.IP "-r|--restore pathname"
Restores git and application data folders found in archive. Pathname example:
.I ./$APPNAME.tar.gz 
.IP -d|--debug
Enable debugging / verbose output
.IP -h|--help
Display help menu
.SH FILES
.I <ruby_gem_dir>/gems/rhc-<version>/conf/express.conf
.RS
The RubyGem system wide configuration file. See
.BR express.conf (5)
for further details.
.RE
.I /etc/openshift/express.conf
.RS
The system wide configuration file. See
.BR express.conf (5)
for further details.
.RE
.I ~/.openshift/express.conf
.RS
Per user configuration file. See
.BR express.conf (5)
for further details.
.RE
.SH BUGS
Please contact the Red Hat OpenShift team.
Forums: http://www.redhat.com/openshift/
IRC: #openshift on irc.freenode.net
.SH AUTHOR
Mike McGrath <mmcgrath@redhat.com>, Jim Jagielski <jimjag@redhat.com>
.SH "SEE ALSO"
.BR rhc-create-app (1),
.BR rhc-ctl-app (1),
.BR rhc-create-domain(1),
.BR rhc-user-info(1),
.BR rhc-tail-files(1),
.BR express.conf (5)
